name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main    # Runs when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use your Node version

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build TypeScript project
        # (Make sure your package.json has "build": "tsc")
      - name: Build project
        run: npm run build

      # 5️⃣ Run tests (optional)
      - name: Run tests
        run: npm test

      # 6️⃣ Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/backend        # path to your app on EC2
            git pull origin main           # pull latest changes
            npm install                    # install deps
            npm run build                  # rebuild TypeScript
            pm2 restart all || pm2 start dist/index.js --name backend
