name: Backend CI/CD

on:
  push:
    branches:
      - main   # Runs when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and build backend
        working-directory: ./Backend
        run: |
          npm install
          npm run build

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/Nuv-e
            git fetch origin main
            git reset --hard origin/main
            cd Backend
            npm install
            npm run build
            pm2 restart backend || pm2 start dist/index.js --name backend
